
version: '3'
services:
  outside_database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    ports:
      - 5432:5432
  outside_redis:
    image: redis:6
    restart: always
    ports:
      - 5555:5555

